from api.models import Company, Vacancy

company1 = Company.objects.create(name="Alpha Tech", description="Leading tech company", city="New York", address="123 Main St")
company2 = Company.objects.create(name="Beta Solutions", description="Innovative solutions", city="San Francisco", address="456 Market St")
company3 = Company.objects.create(name="Gamma Industries", description="Industrial leader", city="Chicago", address="789 Industrial Ave")
company4 = Company.objects.create(name="Delta Corp", description="Consulting experts", city="Boston", address="101 Business Rd")
company5 = Company.objects.create(name="Epsilon Ltd", description="Education and learning", city="Austin", address="202 Learning Blvd")
company6 = Company.objects.create(name="Zeta Systems", description="Cutting-edge systems", city="Seattle", address="303 Tech Park")
company7 = Company.objects.create(name="Eta Group", description="Marketing solutions", city="Los Angeles", address="404 Sunset Blvd")
company8 = Company.objects.create(name="Theta Enterprises", description="Financial services", city="Houston", address="505 Finance St")
company9 = Company.objects.create(name="Iota Technologies", description="Start-up accelerator", city="Denver", address="606 Startup Way")
company10 = Company.objects.create(name="Kappa Logistics", description="Transport and logistics", city="Miami", address="707 Cargo Ln")
company11 = Company.objects.create(name="Lambda Motors", description="Automotive innovations", city="Detroit", address="808 Motorway")
company12 = Company.objects.create(name="Mu Health", description="Healthcare provider", city="Phoenix", address="909 Health Ave")
company13 = Company.objects.create(name="Nu Foods", description="Food industry leader", city="Philadelphia", address="111 Gourmet St")
company14 = Company.objects.create(name="Xi Retail", description="Retail chain", city="Dallas", address="222 Shopping Blvd")
company15 = Company.objects.create(name="Omicron Energy", description="Renewable energy company", city="San Diego", address="333 Solar St")

# Создание вакансий вручную
Vacancy.objects.create(name="Software Engineer", description="Backend development", salary=7000, company=company1)
Vacancy.objects.create(name="Product Manager", description="Manage product lifecycle", salary=7500, company=company2)
Vacancy.objects.create(name="Mechanical Engineer", description="Industrial design", salary=6800, company=company3)
Vacancy.objects.create(name="Business Analyst", description="Consulting services", salary=7200, company=company4)
Vacancy.objects.create(name="Curriculum Developer", description="Education content creation", salary=6000, company=company5)
Vacancy.objects.create(name="System Administrator", description="Maintain IT systems", salary=6700, company=company6)
Vacancy.objects.create(name="Marketing Specialist", description="Advertising campaigns", salary=5900, company=company7)
Vacancy.objects.create(name="Financial Advisor", description="Financial planning", salary=7100, company=company8)
Vacancy.objects.create(name="Start-up Consultant", description="Business development", salary=7300, company=company9)
Vacancy.objects.create(name="Logistics Coordinator", description="Manage shipments", salary=6200, company=company10)
Vacancy.objects.create(name="Automotive Designer", description="Vehicle design", salary=7600, company=company11)
Vacancy.objects.create(name="Medical Assistant", description="Support medical staff", salary=5800, company=company12)
Vacancy.objects.create(name="Food Technologist", description="Food production supervision", salary=6400, company=company13)
Vacancy.objects.create(name="Retail Manager", description="Manage retail store", salary=6100, company=company14)
Vacancy.objects.create(name="Energy Analyst", description="Analyze energy data", salary=7000, company=company15)

print("15 компаний и 15 вакансий успешно созданы!")
